image: Visual Studio 2019

shallow_clone: true

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

only_commits:
  files:
    - src/
    - vc14/
    - appveyor.yml

install:
  - cmd : vcpkg install boost-iostreams:x64-windows
  - cmd : vcpkg install boost-asio:x64-windows
  - cmd : vcpkg install boost-system:x64-windows
  - cmd : vcpkg install boost-filesystem:x64-windows
  - cmd : vcpkg install boost-variant:x64-windows
  - cmd : vcpkg install boost-lockfree:x64-windows
  - cmd : vcpkg install cryptopp:x64-windows
  - cmd : vcpkg install fmt:x64-windows
  - cmd : vcpkg install luajit:x64-windows
  - cmd : vcpkg install --recurse libmariadb:x64-windows
  - cmd : vcpkg install pugixml:x64-windows

build:
  parallel: true
  # MSBuild verbosity level
  #verbosity: detailed

cache:
  - c:\tools\vcpkg\installed\

after_build:
  - 7z a -tzip blueserver-win-%PLATFORM%-%CONFIGURATION%.zip -r %APPVEYOR_BUILD_FOLDER%\vc14\%PLATFORM%\%CONFIGURATION%\*.dll %APPVEYOR_BUILD_FOLDER%\vc14\%PLATFORM%\%CONFIGURATION%\blueserver*.exe %APPVEYOR_BUILD_FOLDER%\data %APPVEYOR_BUILD_FOLDER%\config.lua.dist %APPVEYOR_BUILD_FOLDER%\key.pem %APPVEYOR_BUILD_FOLDER%\LICENSE %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\schema.sql

artifacts:
  - path: vc14\%PLATFORM%\%CONFIGURATION%\blueserver*.exe
  - path: vc14\%PLATFORM%\%CONFIGURATION%\*.dll
  - path: blueserver-win-%PLATFORM%-%CONFIGURATION%.zip
